[project]
name = "getting-started"
version = "0.1.0"
description = "My First Python Project"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cowsay>=6.1",
    "torch>=2.9.1",
    "transformers>=4.57.3",
]
